In [22]:
import pandas as pd
import numpy as np
import scipy.sparse as sp

In [4]:
# 导入数据：分隔符为Tab
raw_data_content = pd.read_csv('/home/zuoyuhui/datasets/cora/cora.content',sep = '\t',header = None)

In [5]:
raw_data_content

0     1     2     3     4     5     6     7     8     9     ...  \
0       31336     0     0     0     0     0     0     0     0     0  ...   
1     1061127     0     0     0     0     0     0     0     0     0  ...   
2     1106406     0     0     0     0     0     0     0     0     0  ...   
3       13195     0     0     0     0     0     0     0     0     0  ...   
4       37879     0     0     0     0     0     0     0     0     0  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
2703  1128975     0     0     0     0     0     0     0     0     0  ...   
2704  1128977     0     0     0     0     0     0     0     0     0  ...   
2705  1128978     0     0     0     0     0     0     0     0     0  ...   
2706   117328     0     0     0     0     1     0     0     0     0  ...   
2707    24043     0     0     0     0     0     0     0     0     0  ...   

      1425  1426  1427  1428  1429  1430  1431  1432  1433  \
0        0     0     1     0     0     0     0     0     0   
1        0     1     0     0     0     0     0     0     0   
2        0     0     0     0     0     0     0     0     0   
3        0     0     0     0     0     0     0     0     0   
4        0     0     0     0     0     0     0     0     0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   
2703     0     0     0     0     0     0     0     0     0   
2704     0     0     0     0     0     0     0     0     0   
2705     0     0     0     0     0     0     0     0     0   
2706     0     0     0     0     0     0     0     0     0   
2707     0     0     0     0     0     0     0     0     0   

                        1434  
0            Neural_Networks  
1              Rule_Learning  
2     Reinforcement_Learning  
3     Reinforcement_Learning  
4      Probabilistic_Methods  
...                      ...  
2703      Genetic_Algorithms  
2704      Genetic_Algorithms  
2705      Genetic_Algorithms  
2706              Case_Based  
2707         Neural_Networks  

[2708 rows x 1435 columns]

In [6]:
# 每行是1435维的向量，第一维是论文的ID，最后一维是论文的Label
raw_data_sample = raw_data_content.head(3)
features_sample =raw_data_sample.iloc[:,1:-1]
labels_sample = raw_data_sample.iloc[:, -1]
labels_onehot_sample = pd.get_dummies(labels_sample)

In [7]:
features_sample

1     2     3     4     5     6     7     8     9     10    ...  1424  \
0     0     0     0     0     0     0     0     0     0     0  ...     0   
1     0     0     0     0     0     0     0     0     0     0  ...     0   
2     0     0     0     0     0     0     0     0     0     0  ...     0   

   1425  1426  1427  1428  1429  1430  1431  1432  1433  
0     0     0     1     0     0     0     0     0     0  
1     0     1     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0     0     0  

[3 rows x 1433 columns]

In [8]:
labels_sample

0           Neural_Networks
1             Rule_Learning
2    Reinforcement_Learning
Name: 1434, dtype: object

In [9]:
labels_onehot_sample

Neural_Networks  Reinforcement_Learning  Rule_Learning
0                1                       0              0
1                0                       0              1
2                0                       1              0

In [10]:
raw_data_cites = pd.read_csv('/home/zuoyuhui/datasets/cora/cora.cites',sep = '\t',header = None)

In [12]:
raw_data_cites.shape

(5429, 2)

In [13]:
raw_data_cites_sample = raw_data_cites.head(10)
raw_data_cites_sample

0        1
0  35     1033
1  35   103482
2  35   103515
3  35  1050679
4  35  1103960
5  35  1103985
6  35  1109199
7  35  1112911
8  35  1113438
9  35  1113831

In [16]:
raw_data_cites.head(10).values.flatten().tolist()

[35,
 1033,
 35,
 103482,
 35,
 103515,
 35,
 1050679,
 35,
 1103960,
 35,
 1103985,
 35,
 1109199,
 35,
 1112911,
 35,
 1113438,
 35,
 1113831]

In [17]:
idx = np.array(raw_data_content.iloc[:, 0], dtype=np.int32)
idx_map = {j: i for i, j in enumerate(idx)}

In [18]:
idx

array([  31336, 1061127, 1106406, ..., 1128978,  117328,   24043],
      dtype=int32)

In [20]:
len(idx_map)

2708

In [25]:
edge_indexs = np.array(list(map(idx_map.get, raw_data_cites.values.flatten())), dtype=np.int32)
edge_indexs

array([ 163,  402,  163, ..., 1887,  837, 1686], dtype=int32)

In [29]:
edge_indexs = edge_indexs.reshape(raw_data_cites.shape)
adjacency = sp.coo_matrix((np.ones(len(edge_indexs)),
            (edge_indexs[:, 0], edge_indexs[:, 1])),
            shape=(edge_indexs.shape[0], edge_indexs.shape[0]), dtype="float32")  #csr_matrix((data, (row_ind, col_ind)), [shape=(M, N)])
raw_data_cites.shape

(5429, 2)

In [26]:
edge_indexs

array([ 163,  402,  163, ..., 1887,  837, 1686], dtype=int32)

In [35]:
adjacency.shape

(5429, 5429)

In [42]:
print(adjacency.todense())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [37]:
print(adjacency)

  (163, 402)	1.0
  (163, 659)	1.0
  (163, 1696)	1.0
  (163, 2295)	1.0
  (163, 1274)	1.0
  (163, 1286)	1.0
  (163, 1544)	1.0
  (163, 2600)	1.0
  (163, 2363)	1.0
  (163, 1905)	1.0
  (163, 1611)	1.0
  (163, 141)	1.0
  (163, 1807)	1.0
  (163, 1110)	1.0
  (163, 174)	1.0
  (163, 2521)	1.0
  (163, 1792)	1.0
  (163, 1675)	1.0
  (163, 1334)	1.0
  (163, 813)	1.0
  (163, 1799)	1.0
  (163, 1943)	1.0
  (163, 2077)	1.0
  (163, 765)	1.0
  (163, 769)	1.0
  :	:
  (2228, 1093)	1.0
  (2228, 1094)	1.0
  (2228, 2068)	1.0
  (2228, 2085)	1.0
  (2694, 2331)	1.0
  (617, 226)	1.0
  (422, 1691)	1.0
  (2142, 2096)	1.0
  (1477, 1252)	1.0
  (1485, 1252)	1.0
  (2185, 2109)	1.0
  (2117, 2639)	1.0
  (1211, 1247)	1.0
  (1884, 745)	1.0
  (1884, 1886)	1.0
  (1884, 1902)	1.0
  (1885, 745)	1.0
  (1885, 1884)	1.0
  (1885, 1886)	1.0
  (1885, 1902)	1.0
  (1886, 745)	1.0
  (1886, 1902)	1.0
  (1887, 2258)	1.0
  (1902, 1887)	1.0
  (837, 1686)	1.0


In [39]:
I = np.array([0,0,1,3,1,0,0])
J = np.array([0,2,1,3,1,0,0])
V = np.array([1,1,1,1,1,1,1])
B = sp.coo_matrix((V,(I,J)),shape=(4,4))
print(B)

  (0, 0)	1
  (0, 2)	1
  (1, 1)	1
  (3, 3)	1
  (1, 1)	1
  (0, 0)	1
  (0, 0)	1


In [40]:
print(B.todense())

[[3 0 1 0]
 [0 2 0 0]
 [0 0 0 0]
 [0 0 0 1]]
